### ISSUE TITLE
About issues without proper information

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group5#19]
Dear all,

Please note that each issue should contain **at least one assignee and label**. Besides these, it should also contain **an explanatory title** as well as **a proper description**. Moreover, even though it is not always possible, try to specify the **priority level** and the **deadline** while writing the issues. Last but not least, try to **distribute the issues equally** among team members both in terms of assignee and owner of the issue (i.e., rather than a few people, every single team member should open a sufficient amount of open issues).

Best,
Meriç

**Comment by kayacanv** [comment]
Hi Meriç,

First of all thanks for your review. We will be careful next time to while adding proper description(also yes, we were going to add labels to issues. Even, we have a team member assigned to check labels).

- But I have a question about "try to distribute the issues equally" ?  We tried to distribute equally in terms of assignee, and  we are getting decisions in the meeting/Slack/WhatsApp, so at the result of the meeting I was going to open the issues to avoid confusion (because all the issues are so similar to each other, and there may be a duplication or a complication such as: who was going to open this issues)
- If we assigned different team member to open each issue, we had to use another system who opened or did not opened yet.  I would like to talk about this topic during the lecture, because I have the impression that in the some of your grading methods there can be misunderstanding.

- And also our planned meeting was in the Wednesday afternoon, the homework shared at the Wednesday evening. Thus, we had to get additional decisions by the help of the online communication channels. I am hoping for your kind understanding on this matter. Next time it will be better for us if homework is published shortly after the lecture.

Thanks in advance,
Kayacan

**Comment by uskudarli** [comment]
Dear Kayacan,


Equal distribution of work is the desired goal (stemming from fairness). It
is not possible to achieve this in a strict manner. Alas, it can be
reasonable. Things will get more tricky when people who are assigned work
do not complete their work. So, let us start with goodwill and focus on how
we can distribute work fairly.

You bring up an important issue as to how to plan and manage the work.
Planning being one of them (and the one you bring up now) can be quite
challenging. The key issue is "trackability".
And, for this, there are some guidelines. But, in the end it has to be
something that the team members can track in practice. For this reason, it
is really important to -- from time to time -- review the results and
practices that you employ. Then, you stick with those that are going well
and tweak/abandon those that are not going well.

I would encourage your team to come up with strategies for managing some of
the work using your online platforms. It will likely take some time to sort
out what works well for you.

The assignment was given in the class when we discussed that you got the
project overview and needed to work on the initial requirements and
elicitation questions.
Everything stated in class is important to follow.  I do try to post the
written form of the assignments timely. Unfortunately, I accidentally
posted the written one elsewhere and corrected this mistake the next day.
The main content was the project description.

In this course, the issue of constraint management and trade-offs never
fade.

Thank you for your well-articulated comment. I look forward to discussing
this issue in class.

**Comment by mericturan** [comment]
I believe that we are all clear after the discussion at today's lecture, so I am closing this issue.
